app = "nginx-stream-forwarder"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

# RTMP service configuration
[[services]]
  internal_port = 1935
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 1935

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
